"""Create leakage-separated private prompts and a negotiation run plan.

Inputs are a score-free public catalogue, public preliminary discussion, public
ordinal priors, and utility profiles generated by ``automatic_utility_profiles``.
Original human score prompts are neither required nor read.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.casefold()).strip("_")


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def fmt_number(value: float | int) -> str:
    number = float(value)
    return str(int(number)) if number.is_integer() else f"{number:g}"


def portable(path: Path, project: Path) -> str:
    """Prefer project-relative paths so the prepared bundle remains movable."""
    try:
        return str(path.resolve().relative_to(project.resolve()))
    except ValueError:
        return str(path.resolve())


def format_catalogue(issues: dict) -> str:
    blocks = []
    for issue, row in sorted(issues.items()):
        lines = [f'Issue {issue}: "{row["title"]}"']
        for option, option_row in sorted(row["options"].items()):
            lines.append(
                f'{option}. "{option_row["title"]}": {option_row["description"]}'
            )
        blocks.append("\n".join(lines))
    return "\n=================\n\n".join(blocks)


def stakeholder_public_position(discussion: dict, stakeholder: str) -> str:
    rows = discussion.get("stakeholders", {}).get(stakeholder, [])
    return "\n\n".join(str(row.get("message", "")).strip() for row in rows if row.get("message"))


def build_private_prompt(
    *,
    stakeholder: str,
    stakeholders: list[str],
    general_context: str,
    issues: dict,
    public_position: str,
    profile_row: dict,
    required_acceptances: int,
) -> str:
    table = profile_row["utility_table"]
    weights = profile_row["issue_weights"]
    threshold = float(profile_row["acceptance_threshold"])
    total = sum(max(options.values()) for options in table.values())
    issue_count = len(table)
    example_deal = ", ".join(sorted(options)[0] for _issue, options in sorted(table.items()))
    ordered_issues = sorted(table, key=lambda issue: (-weights[issue], issue))
    utility_lines = []
    for issue in ordered_issues:
        option_blob = ", ".join(
            f"{option} ({table[issue][option]})" for option in sorted(table[issue])
        )
        utility_lines.append(
            f"Issue {issue} (max score {weights[issue]}): {option_blob}"
        )

    return f"""{general_context.strip()}

The negotiating parties are: {', '.join(stakeholders)}.
You represent the "{stakeholder}". You are an expert negotiator: prepare your answers, pay attention to others, communicate effectively, adapt flexibly, and seek common ground while respecting your minimum acceptable utility.

The predefined issues and options are:

{format_catalogue(issues)}

Your public preliminary position is reproduced below as role context. It is public qualitative information and contains no private score table:

<PUBLIC_PRELIMINARY_POSITION>
{public_position or '[No additional stakeholder-specific public statement was recorded.]'}
</PUBLIC_PRELIMINARY_POSITION>

Your confidential information and preferences for this simulation run:

The following integer utility table was sampled automatically from the public-evidence-constrained utility distribution. It is your private utility function for this run. Other stakeholders do not receive this table.

{chr(10).join(utility_lines)}

The max score you can get is {total}. The score of a complete deal is the sum of the {issue_count} selected option scores.

The full deal must contain exactly one option from every issue.

Confidentiality:
- Never disclose your score table, individual numeric option values, total deal scores, or private tool results in public messages.
- You may communicate qualitative preferences and trade-offs without revealing numbers.

Scoring rules:
- You cannot accept any deal with a score less than {fmt_number(threshold)}. This is the minimum score you can accept.
- If no deal is achieved, your score is {fmt_number(threshold)}.
- You cannot propose more than one option per issue.

Communication format:
- Keep private analysis and calculations inside <SCRATCHPAD>...</SCRATCHPAD>.
- Put only public communication inside <ANSWER>...</ANSWER>.
- Put private next-turn notes inside <PLAN>...</PLAN> when requested.
- Enclose every complete proposed package inside <DEAL>...</DEAL> using comma and one space, for example <DEAL>{example_deal}</DEAL>.

Voting rules:
- Stakeholders take turns to speak; one designated stakeholder acts as voting moderator.
- The voting moderator produces the final candidate proposal after the configured discussion rounds.
- A proposal will pass if at least {required_acceptances} parties agree.
- Accept or reject according to the private score table and the common threshold stated above.
"""


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def parse_names(text: str | None) -> list[str] | None:
    if text is None:
        return None
    return [value.strip() for value in text.split(",") if value.strip()]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Prepare private prompts and run configurations from automatic utility profiles"
    )
    parser.add_argument("--project_dir", default=str(Path(__file__).resolve().parent))
    parser.add_argument("--automatic_scoring_dir", default="automatic_scoring")
    parser.add_argument(
        "--profile_file",
        default=None,
        help="Optional single utility-profile JSON (for example an integer-adapted profile).",
    )
    parser.add_argument("--output_dir", default="automatic_prepared_runs")
    parser.add_argument("--negotiation_output_root", default="automatic_negotiation_outputs")
    parser.add_argument("--model", default="gpt-5.5")
    parser.add_argument("--semantic_model", default="gpt-5.5")
    parser.add_argument("--reasoning_effort", default="high")
    parser.add_argument("--verbosity", default="medium")
    parser.add_argument("--required_acceptances", type=int, default=2)
    parser.add_argument("--moderator", default="Food Safety Authorities")
    parser.add_argument(
        "--moderators",
        default=None,
        help="Comma-separated moderator list. Overrides --moderator; use all four names for a moderator-complete design.",
    )
    parser.add_argument("--runs_per_moderator", type=int, default=1)
    parser.add_argument("--rounds", type=int, default=12)
    parser.add_argument("--window_size", type=int, default=6)
    parser.add_argument("--votes_interval", type=int, default=6)
    parser.add_argument("--posterior_samples", type=int, default=12000)
    parser.add_argument("--max_turns", type=int, default=10)
    parser.add_argument("--base_seed", type=int, default=1729)
    args = parser.parse_args()

    if args.required_acceptances < 1:
        raise ValueError("--required_acceptances must be positive")

    project = Path(args.project_dir).resolve()
    scoring = Path(args.automatic_scoring_dir)
    if not scoring.is_absolute():
        scoring = project / scoring
    output = Path(args.output_dir)
    if not output.is_absolute():
        output = project / output
    negotiation_root = Path(args.negotiation_output_root)
    if not negotiation_root.is_absolute():
        negotiation_root = project / negotiation_root
    output.mkdir(parents=True, exist_ok=True)

    catalogue_path = project / "public_info_Campylobacter" / "public_issue_catalogue.json"
    discussion_path = project / "public_info_Campylobacter" / "preliminary_discussion.json"
    general_path = project / "public_info_Campylobacter" / "General_Description_Campylobacter.txt"
    prior_path = project / "public_priors_Campylobacter.json"
    manifest_path = scoring / "automatic_scoring_manifest.json"
    required_paths = [catalogue_path, discussion_path, general_path, prior_path]
    if args.profile_file is None:
        required_paths.append(manifest_path)
    for path in required_paths:
        if not path.exists():
            raise FileNotFoundError(path)

    catalogue = load_json(catalogue_path)
    discussion = load_json(discussion_path)
    prior = load_json(prior_path)
    scoring_manifest = load_json(manifest_path) if args.profile_file is None else None
    issues = catalogue["issues"]
    stakeholders = list(prior["stakeholders"])
    moderators = parse_names(args.moderators) or [args.moderator]
    unknown_moderators = sorted(set(moderators) - set(stakeholders))
    if unknown_moderators:
        raise ValueError(f"Unknown moderator(s) {unknown_moderators!r}; choose from {stakeholders}")
    if args.required_acceptances > len(stakeholders):
        raise ValueError("Required acceptances exceed stakeholder count")
    if args.runs_per_moderator < 1:
        raise ValueError("--runs_per_moderator must be positive")
    if set(discussion.get("stakeholders", {})) != set(stakeholders):
        raise ValueError("Preliminary-discussion stakeholder set differs from the prior")
    general_context = general_path.read_text(encoding="utf-8-sig")

    planned_runs = []
    profile_manifests = []
    counter = 0
    if args.profile_file is None:
        profile_records = [(scoring / record["path"]).resolve() for record in scoring_manifest["profiles"]]
    else:
        profile_candidate = Path(args.profile_file)
        profile_records = [(profile_candidate if profile_candidate.is_absolute() else project / profile_candidate).resolve()]
    for profile_path in profile_records:
        profile = load_json(profile_path)
        profile_id = profile["profile_id"]
        profile_root = output / profile_id
        prompt_dir = profile_root / "private_prompts"
        config_dir = profile_root / "moderator_configs"
        deal_dir = profile_root / "initial_deals"
        prompt_dir.mkdir(parents=True, exist_ok=True)
        config_dir.mkdir(parents=True, exist_ok=True)
        deal_dir.mkdir(parents=True, exist_ok=True)

        prompt_paths: dict[str, Path] = {}
        for stakeholder in stakeholders:
            row = profile["stakeholders"][stakeholder]
            prompt_path = prompt_dir / f"{slug(stakeholder)}.txt"
            prompt_path.write_text(
                build_private_prompt(
                    stakeholder=stakeholder,
                    stakeholders=stakeholders,
                    general_context=general_context,
                    issues=issues,
                    public_position=stakeholder_public_position(discussion, stakeholder),
                    profile_row=row,
                    required_acceptances=args.required_acceptances,
                ),
                encoding="utf-8",
            )
            prompt_paths[stakeholder] = prompt_path

        profile_files = []
        for moderator in moderators:
            moderator_slug = slug(moderator)
            deal = profile["stakeholders"][moderator]["preferred_deal"]["canonical_starting_deal"]
            deal_path = deal_dir / f"initial_deal_{moderator_slug}.txt"
            deal_path.write_text(deal + "\n", encoding="utf-8")
            config_path = config_dir / f"moderator_{moderator_slug}.txt"
            lines = []
            for stakeholder in stakeholders:
                role = "negotiator&voting_moderator" if stakeholder == moderator else "negotiator"
                lines.append(
                    f"{stakeholder},{portable(prompt_paths[stakeholder], project)},{role},{args.model},"
                    f"{args.reasoning_effort},{args.verbosity}"
                )
            config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            profile_files.extend([deal_path, config_path])

            for repetition in range(1, args.runs_per_moderator + 1):
                run_seed = args.base_seed + counter
                run_id = f"{profile_id}_{moderator_slug}_moderator_run_{repetition}_seed_{run_seed}"
                run_output = negotiation_root / run_id
                command = [
                "python", "main_campy_bayesian_negotiation.py",
                "--agents_num", str(len(stakeholders)),
                "--rounds", str(args.rounds),
                "--window_size", str(args.window_size),
                "--votes_interval", str(args.votes_interval),
                "--initial_prompts_file", portable(config_path, project),
                "--initial_deal_file", portable(deal_path, project),
                "--public_prior_file", portable(prior_path, project),
                "--semantic_model", args.semantic_model,
                "--posterior_samples", str(args.posterior_samples),
                "--prior_mode", "semantic",
                "--random_seed", str(run_seed),
                "--output_dir", portable(run_output, project),
                "--sleep_seconds", "0",
                "--reasoning_effort", args.reasoning_effort,
                "--verbosity", args.verbosity,
                "--max_turns", str(args.max_turns),
                "--minimum_accepting_stakeholders", str(args.required_acceptances),
                ]
                planned_runs.append({
                "run_id": run_id,
                "profile_id": profile_id,
                "profile_file": portable(profile_path, project),
                "moderator": moderator,
                "repetition": repetition,
                "seed": run_seed,
                "initial_deal": deal,
                "initial_deal_file": portable(deal_path, project),
                "configuration": portable(config_path, project),
                "output_dir": portable(run_output, project),
                "command": command,
                "status": "prepared_not_run",
                })
                counter += 1

        for path in prompt_paths.values():
            profile_files.append(path)
        profile_manifest = {
            "profile_id": profile_id,
            "source_profile": portable(profile_path, project),
            "source_profile_sha256": sha256_file(profile_path),
            "human_score_prompts_used": False,
            "files": [
                {"path": portable(path, project), "sha256": sha256_file(path)}
                for path in sorted(set(profile_files))
            ],
        }
        profile_manifest_path = profile_root / "prompt_manifest.json"
        profile_manifest_path.write_text(
            json.dumps(profile_manifest, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        profile_manifests.append({
            "profile_id": profile_id,
            "path": portable(profile_manifest_path, project),
            "sha256": sha256_file(profile_manifest_path),
        })

    plan_payload = {
        "schema": "automatic_negotiation_run_plan_v1",
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "status": "prepared_not_run",
        "design": (
            "Each configured profile × moderator × repetition is prepared separately; every moderator "
            "opens with its own maximum-utility package and produces the final candidate proposal."
        ),
        "human_score_tables_used": False,
        "public_prior_file": portable(prior_path, project),
        "public_prior_sha256": sha256_file(prior_path),
        "automatic_scoring_manifest": portable(manifest_path, project) if manifest_path.exists() else None,
        "automatic_scoring_manifest_sha256": sha256_file(manifest_path) if manifest_path.exists() else None,
        "stakeholders": stakeholders,
        "profiles": len(profile_records),
        "moderators_per_profile": len(moderators),
        "selected_moderator": args.moderator if len(moderators) == 1 else None,
        "selected_moderators": moderators,
        "repetitions_per_profile_moderator": args.runs_per_moderator,
        "total_planned_runs": len(planned_runs),
        "rounds": args.rounds,
        "window_size": args.window_size,
        "votes_interval": args.votes_interval,
        "required_acceptances": args.required_acceptances,
        "negotiation_model": args.model,
        "semantic_model": args.semantic_model,
        "posterior_samples": args.posterior_samples,
        "profile_manifests": profile_manifests,
        "runs": planned_runs,
    }
    json_path = output / "experiment_plan.json"
    json_path.write_text(json.dumps(plan_payload, indent=2, ensure_ascii=False), encoding="utf-8")
    csv_path = output / "experiment_plan.csv"
    fields = [
        "run_id", "profile_id", "moderator", "repetition", "seed", "initial_deal",
        "configuration", "initial_deal_file", "output_dir", "status",
    ]
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows({key: row[key] for key in fields} for row in planned_runs)
    print(f"Prepared {len(planned_runs)} negotiation runs; no model API was called.")
    print(f"Run plan: {json_path}")


if __name__ == "__main__":
    main()
